### ISSUE TITLE
Once more heroku has updated postgres and this stopped working

### ISSUE THREAD

**Issue by sebschlo** [bfirsh/heroku-tarsnap-backups#6]
I'm getting the following error. 
```
pg_dump: error: server version: 14.7 (Ubuntu 14.7-1.pgdg20.04+1); pg_dump version: 13.6
pg_dump: error: aborting because of server version mismatch
```

In the past, I submitted a PR to update the alpine version of the docker image to one that would have the right version of postgres and pgdump. However, postgres is not even included in the more recent Alpine distributions. So I started looking at using another image, perhaps a debian based one, but I'm seeing that it's non trivial to install `tarsnap` on debian because you have to add a key and then add an apt repo to your system https://www.tarsnap.com/pkg-deb.html 

@bfirsh I'm happy to do this work, but I wanted to get your opinion on the best path forward here, whether to proceed with a debian image, or use something else. Thanks!

**Comment by bfirsh** [comment]
Hello :D

I've added you as a maintainer. Feel free to update as you see fit. :)

I'm not very good at keeping on top of my notifications. Feel free to email me if I miss things ben@firshman.com

**Comment by sebschlo** [comment]
Hey, sounds good! happy to keep maintaining it :) the invitation you sent
expired, unfortunately, mind sending it again?

**Comment by bfirsh** [comment]
Done!

**Comment by sebschlo** [comment]
#7
